### ISSUE TITLE
composer requirements failing

### ISSUE THREAD

**Issue by OlliM** [ibrows/PaymentSaferpayBundle#1]
Problem 1
    - Installation request for ibrows/payment-saferpay-bundle dev-master -> satisfiable by ibrows/payment-saferpay-bundle[dev-master].
    - ibrows/payment-saferpay-bundle dev-master requires payment/saferpay-bundle dev-master -> no matching package found.

Any ideas?

**Comment by Gladhon** [comment]
Thx for your input. Sorry, we don't maintain this bundle any more.

We use payment/saferpay-bundle instead
https://packagist.org/packages/payment/saferpay-bundle
